"""Golden scenario for a legacy (models IS NULL) session.

Runs the real InferenceLoopService on a scripted fall_detection stream and
returns a normalised trace: runtime calls, the detection payload visible at
each call, violations written, session counters. Uses only APIs that exist
before M1, so the expected trace is generated by running this very module
against the pre-M1 code (see golden_legacy_trace.json).

    python -m tests.multi_model.legacy_scenario <asyncpg-url> <trace.json>
"""

import asyncio
import json
import sys
import uuid
from datetime import datetime, timezone

from sqlalchemy import select, text

from tests.multi_model.fakes import (
    FakeRuntime,
    FakeVAS,
    result,
    session_factory_for,
    stop_loop,
    wait_for,
)

PATTERN = [False, True, True, False, True, True, True, False, True]
CONFIG = {"zones": [{"id": "z1", "points": [[0, 0], [10, 0], [10, 10]]}]}


async def run_legacy_scenario(sessionmaker) -> dict:
    import app.services.inference_loop as il
    from app.models import Device, StreamSession, StreamState, Violation

    saved = (il.TARGET_FPS, il.MAX_GPU_UTILIZATION)
    il.TARGET_FPS, il.MAX_GPU_UTILIZATION = 50.0, 100.0
    try:
        async with sessionmaker() as db:
            await db.execute(text("TRUNCATE violations, stream_sessions, devices CASCADE"))
            device = Device(vas_device_id=str(uuid.uuid4()), name="golden camera", is_active=True)
            db.add(device)
            await db.flush()
            session = StreamSession(
                device_id=device.id,
                model_id="fall_detection",
                model_version="1.0.0",
                model_config=CONFIG,
                state=StreamState.LIVE,
                vas_stream_id=str(uuid.uuid4()),
                started_at=datetime.now(timezone.utc),
            )
            db.add(session)
            await db.commit()
            device_id, session_id = device.id, session.id

        def script(model_id, n):
            if n >= len(PATTERN):
                return None
            return result(PATTERN[n], confidence=0.8 + n / 100, label="fall_detected")

        runtime = FakeRuntime(script)
        loop = il.InferenceLoopService(
            runtime_router=runtime,
            vas_client=FakeVAS(),
            db_session_factory=session_factory_for(sessionmaker),
            loop_interval=0.02,
        )
        visible = []

        def snapshot(_model_id, _n):
            payload = loop.get_latest_detection(device_id)
            if payload is not None:
                payload = {k: v for k, v in payload.items() if k != "age_ms"}
            visible.append(payload)

        runtime.on_call = snapshot
        await loop.start()
        # The call after the last scripted one parks forever: by then every
        # scripted result has been fully processed (violations included).
        await wait_for(lambda: runtime.count["fall_detection"] > len(PATTERN))
        await stop_loop(loop)

        async with sessionmaker() as db:
            violations = (
                await db.execute(
                    select(Violation)
                    .where(Violation.stream_session_id == session_id)
                    .order_by(Violation.created_at)
                )
            ).scalars().all()
            row = await db.get(StreamSession, session_id)
            counters = {
                "frames_processed": row.frames_processed,
                "violations_count": row.violations_count,
            }

        def norm(value):
            text_value = json.dumps(value, sort_keys=True, default=str)
            for real, placeholder in ((device_id, "<device>"), (session_id, "<session>")):
                text_value = text_value.replace(str(real), placeholder)
            return json.loads(text_value)

        return norm(
            {
                "calls": [
                    {k: c[k] for k in ("kind", "model_id", "n", "config")} for c in runtime.calls
                ],
                "visible_detection_at_each_call": visible,
                "violations": [
                    {
                        "type": v.type.value,
                        "type_detail": v.type_detail,
                        "model_id": v.model_id,
                        "model_version": v.model_version,
                        "confidence": v.confidence,
                        "bounding_boxes": v.bounding_boxes,
                        "status": v.status.value,
                    }
                    for v in violations
                ],
                "counters": counters,
                "max_in_flight": dict(runtime.max_in_flight),
            }
        )
    finally:
        il.TARGET_FPS, il.MAX_GPU_UTILIZATION = saved


if __name__ == "__main__":
    from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

    async def _main(url: str, out_path: str) -> None:
        engine = create_async_engine(url)
        trace = await run_legacy_scenario(async_sessionmaker(engine, expire_on_commit=False))
        await engine.dispose()
        # Written to a file: the app's structured logs go to stdout.
        with open(out_path, "w") as out:
            json.dump(trace, out, indent=2, sort_keys=True)
            out.write("\n")

    asyncio.run(_main(sys.argv[1], sys.argv[2]))
